"""v3

Revision ID: 9a6b2dc26267
Revises: b197a71ccc5a
Create Date: 2026-08-16 15:19:40.256434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6b2dc26267'
down_revision: Union[str, Sequence[str], None] = 'b197a71ccc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_user_agent_name', 'agents', ['user_id', 'agent_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_agent_name', 'agents', type_='unique')
    op.drop_column('agents', 'agent_name')
    # ### end Alembic commands ###
